<?xml version="1.0"?>
<!DOCTYPE class [
    <!ELEMENT class (student+)>
    <!ELEMENT student (firstname, lastname, nickname, marks)>
    <!ATTLIST student rollno CDATA #REQUIRED>
    <!ELEMENT firstname (#PCDATA)>
    <!ELEMENT lastname (#PCDATA)>
    <!ELEMENT nickname (#PCDATA)>
    <!ELEMENT marks (#PCDATA)>
]>
<class>
    <student rollno="393">
        <firstname>dinkar</firstname>
        <lastname>kad</lastname>
        <nickname>dinkar</nickname>
        <marks>85</marks>
    </student>

    <student rollno="493">
        <firstname>vaneet</firstname>
        <lastname>Gupta</lastname>
        <nickname>vinni</nickname>
        <marks>95</marks>
    </student>

    <student rollno="593">
        <firstname>jasvir</firstname>
        <lastname>singh</lastname>
        <nickname>jazz</nickname>
        <marks>90</marks>
    </student>
</class>